# IMPORT NECESSARY LIBRARIES

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb

# DATA ON BOARD

In [ ]:
from google.colab import files
a=files.upload()

Saving svm classifier.csv to svm classifier.csv


# DESCRIPTIVE ANALYSIS
# DATA PREPROCESSING/EDA

In [ ]:
df=pd.read_csv('svm classifier.csv')

In [ ]:
df.tail()

gender married   ch  income  loanamt status
609  Female      No  1.0    2900     71.0      Y
610    Male     Yes  1.0    4106     40.0      Y
611    Male     Yes  1.0    8072    253.0      Y
612    Male     Yes  1.0    7583    187.0      Y
613  Female      No  0.0    4583    133.0      N

In [ ]:
df.head()

gender married   ch  income  loanamt status
0   Male      No  1.0    5849      NaN      Y
1   Male     Yes  1.0    4583    128.0      N
2   Male     Yes  1.0    3000     66.0      Y
3   Male     Yes  1.0    2583    120.0      Y
4   Male      No  1.0    6000    141.0      Y

In [ ]:
df.columns

Index(['gender', 'married', 'ch', 'income', 'loanamt', 'status'], dtype='object')

In [ ]:
df.shape

(614, 6)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   gender   601 non-null    object 
 1   married  611 non-null    object 
 2   ch       564 non-null    float64
 3   income   614 non-null    int64  
 4   loanamt  592 non-null    float64
 5   status   614 non-null    object 
dtypes: float64(2), int64(1), object(3)
memory usage: 28.9+ KB


In [ ]:
df.describe()

ch        income     loanamt
count  564.000000    614.000000  592.000000
mean     0.842199   5403.459283  146.412162
std      0.364878   6109.041673   85.587325
min      0.000000    150.000000    9.000000
25%      1.000000   2877.500000  100.000000
50%      1.000000   3812.500000  128.000000
75%      1.000000   5795.000000  168.000000
max      1.000000  81000.000000  700.000000

# NULL VALUE DEDUCTION

In [ ]:
df.isnull().sum()

gender     13
married     3
ch         50
income      0
loanamt    22
status      0
dtype: int64

In [ ]:
df1 = df.copy()

# DROPPING LESS IMPORTANT FEATURES

In [ ]:
df = df.drop(['ch'],axis=1)

In [ ]:
df

gender married  income  loanamt status
0      Male      No    5849      NaN      Y
1      Male     Yes    4583    128.0      N
2      Male     Yes    3000     66.0      Y
3      Male     Yes    2583    120.0      Y
4      Male      No    6000    141.0      Y
..      ...     ...     ...      ...    ...
609  Female      No    2900     71.0      Y
610    Male     Yes    4106     40.0      Y
611    Male     Yes    8072    253.0      Y
612    Male     Yes    7583    187.0      Y
613  Female      No    4583    133.0      N

[614 rows x 5 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   gender   601 non-null    object 
 1   married  611 non-null    object 
 2   income   614 non-null    int64  
 3   loanamt  592 non-null    float64
 4   status   614 non-null    object 
dtypes: float64(1), int64(1), object(3)
memory usage: 24.1+ KB


# FILL NAN VALUES OF THE PARTICULAR DATASET

In [ ]:
num = ['loanamt']

In [ ]:
df[num] = df[num].fillna(df[num].mean())

In [ ]:
df.isnull().sum()

gender     13
married     3
income      0
loanamt     0
status      0
dtype: int64

In [ ]:
categorical = ['gender','married']

In [ ]:
df[categorical] = df[categorical].fillna(df.mode().iloc[0])

In [ ]:
df.isnull().sum()

gender     0
married    0
income     0
loanamt    0
status     0
dtype: int64

In [ ]:
cleaned_data = df.copy()

# LABEL ENCODING FOR THE CATEGORICAL FEATURES

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
lb = LabelEncoder()

In [ ]:
df['newgender'] = lb.fit_transform(df['gender'])

In [ ]:
df['t_married'] = lb.fit_transform(df['married'])

In [ ]:
df['newstatus'] = lb.fit_transform(df['status'])

In [ ]:
df

gender married  income     loanamt status  newgender  t_married  \
0      Male      No    5849  146.412162      Y          1          0   
1      Male     Yes    4583  128.000000      N          1          1   
2      Male     Yes    3000   66.000000      Y          1          1   
3      Male     Yes    2583  120.000000      Y          1          1   
4      Male      No    6000  141.000000      Y          1          0   
..      ...     ...     ...         ...    ...        ...        ...   
609  Female      No    2900   71.000000      Y          0          0   
610    Male     Yes    4106   40.000000      Y          1          1   
611    Male     Yes    8072  253.000000      Y          1          1   
612    Male     Yes    7583  187.000000      Y          1          1   
613  Female      No    4583  133.000000      N          0          0   

     newstatus  
0            1  
1            0  
2            1  
3            1  
4            1  
..         ...  
609          1  
610          1  
611          1  
612          1  
613          0  

[614 rows x 8 columns]

In [ ]:
df.drop('gender',axis=1,inplace=True)

In [ ]:
df.drop('married',axis=1,inplace=True)

In [ ]:
df.drop('status',axis=1,inplace=True)

In [ ]:
df

income     loanamt  newgender  t_married  newstatus
0      5849  146.412162          1          0          1
1      4583  128.000000          1          1          0
2      3000   66.000000          1          1          1
3      2583  120.000000          1          1          1
4      6000  141.000000          1          0          1
..      ...         ...        ...        ...        ...
609    2900   71.000000          0          0          1
610    4106   40.000000          1          1          1
611    8072  253.000000          1          1          1
612    7583  187.000000          1          1          1
613    4583  133.000000          0          0          0

[614 rows x 5 columns]

# X AND Y SPLIT

In [ ]:
x= df.iloc[:,0:4]
y = df.iloc[:,-1]

# ACCORDING TO THE PARADO LOGIC WE HAVE TO SPLIT X AND Y AS
# 80 - 20
# 70 - 30
# 75 - 25 (MAXIMUM SPLIT)
# TRAIN TEST SPLIT

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=23)

# USING SUPERVISED MODEL LOGISTICAL REGRESSION TO TRAIN A ML MODEL

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
log_reg = LogisticRegression(random_state=0)

In [ ]:
log_reg.fit(x_train,y_train)

LogisticRegression(random_state=0)

In [ ]:
y_predict = log_reg.predict(x_test)

# EVALUATION METRICS FOR THE SUPERVISED LOGISTICAL REGRESSION MODEL

In [ ]:
from sklearn.metrics import confusion_matrix,recall_score,accuracy_score,precision_score,f1_score

In [ ]:
cmlog_reg =  confusion_matrix(y_test,y_predict)
recall = recall_score(y_test,y_predict)
accuracy = accuracy_score(y_test,y_predict)
precision = precision_score(y_test,y_predict)
f1score = f1_score(y_test,y_predict)

In [ ]:
print('CONFUSION METRICS   ','\n',cmlog_reg)
print()
print(' RECALLSCORE   = ',recall)
print('ACCURACYSCORE  = ',accuracy)
print('PRECISIONSCORE = ',precision)
print('    F1SCORE    = ',f1score)

CONFUSION METRICS    
 [[  0  71]
 [  0 114]]

 RECALLSCORE   =  1.0
ACCURACYSCORE  =  0.6162162162162163
PRECISIONSCORE =  0.6162162162162163
    F1SCORE    =  0.7625418060200669


In [ ]:
df1 = df.copy()

In [ ]:
cleaneddata = df1.copy()

In [ ]:
x= df1.iloc[:,0:4]
y = df1.iloc[:,-1]

# WITH THE HELP OF BASE LEANER KNN CLASSIFIER ALGORITHM TO TRAIN A ML MODEL

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=23)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
knn = KNeighborsClassifier(n_neighbors=5)

In [ ]:
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [ ]:
y_predict = knn.predict(x_test)

# Evaluation metrics

In [ ]:
from sklearn.metrics import confusion_matrix,recall_score,accuracy_score,precision_score,f1_score

In [ ]:
cmknn = confusion_matrix(y_test,y_predict)
recall = recall_score(y_test,y_predict)
accuracy = accuracy_score(y_test,y_predict)
precision = precision_score(y_test,y_predict)
f1score = f1_score(y_test,y_predict)
print('CONFUSIONMETRICS  ','\n',cmknn)
print()
print(' RECALLSCORE   = ',recall)
print('ACCURACYSCORE  = ',accuracy)
print('PRECISIONSCORE = ',precision)
print('   F1SCORE     = ',f1score)

CONFUSIONMETRICS   
 [[11 60]
 [16 98]]

 RECALLSCORE   =  0.8596491228070176
ACCURACYSCORE  =  0.5891891891891892
PRECISIONSCORE =  0.620253164556962
   F1SCORE     =  0.7205882352941176


#  WITH THE HELP OF SVM CLASSFIER ALGORITHM GOING EVALUATE THE METRICS



In [ ]:
df2 = cleaneddata.copy()

In [ ]:
x= df2.iloc[:,0:4]
y = df2.iloc[:,-1]

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=23)

In [ ]:
from sklearn.svm import SVC
svm = SVC()
svm.fit(x_train,y_train)

SVC()

In [ ]:
ypredict = svm.predict(x_test)

In [ ]:
from sklearn.metrics import confusion_matrix,recall_score,accuracy_score,precision_score,f1_score
cmsvm = confusion_matrix(y_test,ypredict)
recall = recall_score(y_test,ypredict)
accuracy=accuracy_score(y_test,ypredict)
precision = precision_score(y_test,ypredict)
f1score = f1_score(y_test,ypredict)
print('CONFUSION METRICS','\n',cmsvm)
print()
print('RECALLSCORE    = ',recall)
print('ACCURACYSCORE  = ',accuracy)
print('PRECISIONSCORE = ',precision)
print('    F1SCORE    = ',f1score)

CONFUSION METRICS 
 [[  0  71]
 [  0 114]]

RECALLSCORE    =  1.0
ACCURACYSCORE  =  0.6162162162162163
PRECISIONSCORE =  0.6162162162162163
    F1SCORE    =  0.7625418060200669


# A ML Model is learning better in SVM and LOGISTICAL REGRESSION algorithm better than KNN algorithm.so,i recommend according to the ACCURACYSCORE either in SVM or LOGISTICAL REGRESSION algorithm we will build a model to predict the loanstatus(y variable).